# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-07-18 10:50:16
"""
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Soils_Aurora = "C:\\Users\\brett\\OneDrive\\Documents\\ArcGIS\\Projects\\ESRI Training\\ProIntegratingData\\AuroraPlanning\\AuroraRail.gdb\\Soils_Aurora"
    Railroads_Aurora = "Railroads_Aurora"

    # Process: Pairwise Buffer (Pairwise Buffer) (analysis)
    Railroads_Aurora_Buffer = "C:\\Users\\brett\\OneDrive\\Documents\\ArcGIS\\Projects\\ESRI Training\\ProIntegratingData\\AuroraPlanning\\AuroraRail.gdb\\Railroads_Aurora_Buffer"
    arcpy.analysis.PairwiseBuffer(in_features=Railroads_Aurora, out_feature_class=Railroads_Aurora_Buffer, buffer_distance_or_field="200 Feet", dissolve_option="ALL")

    # Process: Pairwise Clip (Pairwise Clip) (analysis)
    Soils_RR_Interaction = "C:\\Users\\brett\\OneDrive\\Documents\\ArcGIS\\Projects\\ESRI Training\\ProIntegratingData\\AuroraPlanning\\AuroraRail.gdb\\Soils_RR_Interaction"
    arcpy.analysis.PairwiseClip(in_features=Soils_Aurora, clip_features=Railroads_Aurora_Buffer, out_feature_class=Soils_RR_Interaction)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\brett\\OneDrive\\Documents\\ArcGIS\\Projects\\ESRI Training\\ProIntegratingData\\AuroraPlanning\\AuroraRail.gdb", workspace="C:\\Users\\brett\\OneDrive\\Documents\\ArcGIS\\Projects\\ESRI Training\\ProIntegratingData\\AuroraPlanning\\AuroraRail.gdb"):
        Model()
